# fly.toml app configuration file generated for cvgen-c-jysq on 2025-07-19T12:52:12-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cvgen-c-jysq'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  # Environment variables will be set via fly secrets command
  # OPENROUTER_API_KEY should be set using: fly secrets set OPENROUTER_API_KEY=your_api_key_here
